name: Sync Fork at 6am

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6am UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch upstream changes
        run: git fetch upstream
      - name: Merge upstream changes
        run: git merge upstream/main --no-edit
      - name: Push changes to forked repo
        run: git push origin main
