name: Sync Fork at 6am

on:
  schedule:
    - cron: '42 14 * * *'  # Runs every day at 6am UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add the link to the main repo
        run: git remote add upstream https://github.com/EddieHubCommunity/BioDrop.git
      - name: Fetch upstream changes
        run: git fetch upstream
      - name: Merge upstream changes
        run: |
          git config user.email emmysoetan@gmail.com
          git config user.name Shoetan
          git merge upstream/main --no-edit --allow-unrelated-histories
      - name: Push changes to forked repo
        run: git push origin main
